config/routes.rb
BestComics::Application.routes.draw do
  resources :comic_requests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :comics do
    resources :ratings, :controller => "comic_ratings"
  end
  
  resources :users do
    resources :ratings
  end
  
  match 'user_comic_list/:user_name' => 'ratings#user_comic_list', :as => "user_comic_list"
  match 'comics/author/:author_name' => 'comics#author_search'
  
  root :to => "home#index"

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  extend ActiveSupport::Memoizable
  
  # acts_as_commentable
  # acts_as_taggable
  # acts_as_rateable
  
  has_many :ratings
  
  def update_statistics!
    self.rating_count = self.number_of_ratings
    self.average_score = self.average_rating
    self.save!
  end
  
  protected 
  
  def average_rating
    if self.number_of_ratings > 0
      self.ratings.sum(:rating) / self.number_of_ratings.to_f
    else
      0
    end
  end
  memoize :average_rating
  
  def number_of_ratings
    self.ratings.size
  end
  memoize :number_of_ratings
  
  # @post.rate_it( 4, current_user.id )
  # 
  # @post.average_rating #=> 4.0
  # 
  # @post.average_rating_round #=> 4
  # 
  # @post.average_rating_percent #=> 80
  # 
  # @post.rated_by?( current_user ) #=> rating || false
  # 
  # Post.find_average_of( 4 ) #=> array of posts  


  
  # commentable = Post.create
  # commentable.comments.create(:title => "First comment.", :comment => "This is the first comment.")


  
  # @user = User.new(:name => "Bobby")
  #    @user.tag_list = "awesome, slick, hefty"      # this should be familiar
  #    @user.save  
  
  # class User < ActiveRecord::Base
  #   acts_as_taggable_on :tags
  #   named_scope :by_join_date, :order => "created_at DESC"
  # end
  # 
  # User.tagged_with("awesome").by_date
  # User.tagged_with("awesome").by_date.paginate(:page => params[:page], :per_page => 20)
  # 
  # # Find a user with matching all tags, not just one
  # User.tagged_with(["awesome", "cool"], :match_all => :true)
  # 
  # # Find a user with any of the tags:
  # User.tagged_with(["awesome", "cool"], :any => true)  
  
  # @frankie = User.find_by_name("Frankie")
  #   @frankie.skill_list # => ["hacking"]
  # 
  #   @tom = User.find_by_name("Tom")
  #   @tom.skill_list # => ["hacking", "jogging", "diving"]
  # 
  #   @tom.find_related_skills # => [<User name="Bobby">,<User name="Frankie">]
  #   @bobby.find_related_skills # => [<User name="Tom">]
  #   @frankie.find_related_skills # => [<User name="Tom">]  
  
  
  # @user = User.new(:name => "Bobby")
  #    @user.set_tag_list_on(:customs, "same, as, tag, list")
  #    @user.tag_list_on(:customs) # => ["same","as","tag","list"]
  #    @user.save
  #    @user.tags_on(:customs) # => [<Tag name='same'>,...]
  #    @user.tag_counts_on(:customs)
  #    User.tagged_with("same", :on => :customs) # => [@user]
  
  # <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  #   <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
  # <% end %>  
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  # GET /comics
  # GET /comics.xml
  def index
    @comics = Comic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.xml
  def show
    @comic = Comic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comic }
    end
  end
  
  def author_search
    @author_name = params[:author_name]
    @comics = Comic.where(:author => params[:author_name])
    if !@comics.any?
      redirect_to root_path, :notice => "No comics found for this author."
    end
  end
  
  # 
  # # GET /comics/new
  # # GET /comics/new.xml
  # def new
  #   @comic = Comic.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.xml  { render :xml => @comic }
  #   end
  # end
  # 
  # # GET /comics/1/edit
  # def edit
  #   @comic = Comic.find(params[:id])
  # end
  # 
  # # POST /comics
  # # POST /comics.xml
  # def create
  #   @comic = Comic.new(params[:comic])
  # 
  #   respond_to do |format|
  #     if @comic.save
  #       format.html { redirect_to(@comic, :notice => 'Comic was successfully created.') }
  #       format.xml  { render :xml => @comic, :status => :created, :location => @comic }
  #     else
  #       format.html { render :action => "new" }
  #       format.xml  { render :xml => @comic.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # PUT /comics/1
  # # PUT /comics/1.xml
  # def update
  #   @comic = Comic.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @comic.update_attributes(params[:comic])
  #       format.html { redirect_to(@comic, :notice => 'Comic was successfully updated.') }
  #       format.xml  { head :ok }
  #     else
  #       format.html { render :action => "edit" }
  #       format.xml  { render :xml => @comic.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /comics/1
  # # DELETE /comics/1.xml
  # def destroy
  #   @comic = Comic.find(params[:id])
  #   @comic.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to(comics_url) }
  #     format.xml  { head :ok }
  #   end
  # end
end

app/helpers/comics_helper.rb
module ComicsHelper
  def suggest_comics_link
    link_to I18n.t('user_ratings.link.cannot_see_your_favourite_comic'), new_comic_request_path
  end
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :book_cover_image_url %><br />
    <%= f.text_field :book_cover_image_url %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('link.save') %>
  </div>
<% end %>

app/views/comics/_top_comics.html.erb
<section id="<%= section_name %>-section" class="top-rated-sections">
<h2><%= section_title %></h2>

<div id="<%= section_name %>-helper-links" class="section-helper-links">
  <div class="more-links link-to-actions">
    <%= will_paginate comics, :prev_label => I18n.t('link.prev'),
  :next_label => I18n.t('link.next') %>
  </div>
</div>

<% comics.each_with_index do |comic, index| %>
  <div id="<%= section_name %>-<%= index %>" class="<%= section_name %>-comics top-rated-comics">
    <div class="section-left">
      <div class="comic-book-cover">
        <img src="<%= comic.book_cover_image_url %>" />
      </div>
    </div>
    <div class="section-middle">
      <div class="comic-name"><%= comic.name %></div>
      <div class="comic-author"><%= link_to comic.author, "/comics/author/#{comic.author}" %></div>
      <div class="comic-rating"><%= comic.average_score %> / 10 (<%= comic.rating_count %>)</div>
      <div class="comic-is-finished"><%= comic.is_finished ? I18n.t("options.finished") : I18n.t("options.not_finished") %></div>
    </div>
    <div class="section-right">    
      <div class="rating-widgets">
        <div class="link-to-actions">
          <%= link_to I18n.t('home.link.rate_this'), new_comic_rating_path(comic) %>
        </div>
        <div class="link-to-actions">        
          <%= link_to I18n.t('home.link.read_online'), comic.online_reading_website_url ? comic.online_reading_website_url : "/#" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div id="<%= section_name %>-helper-links" class="section-helper-links">
  <div class="more-links link-to-actions">
      <%= will_paginate comics, :prev_label => I18n.t('link.prev'),
    :next_label => I18n.t('link.next') %>
  </div>
</div>

</section>

app/views/comics/_user_comic_list.html.erb
<section id="<%= section_name %>-section" class="user-comic-list-sections">
<h3><%= section_title %></h3>

<% user_comic_lists.each_with_index do |list, index| %>
  <div id="<%= section_name %>-<%= index %>" class="<%= section_name %>-comic-lists user-comic-lists">
    <div class="list-index"><%= index + 1 %>.</div>
    <div class="list-user-username">
    <%= link_to list.user.username, user_comic_list_url(:user_name => list.user.username) if list.user.username %> 
    </div>
    <div class="list-rating-count">(<%= list.count %>)</div>
  </div>
<% end %>

</section>

app/views/comics/author_search.html.erb
<h1><%= @author_name %><%= I18n.t('comics.author.list.title') %></h1>

<table>
  <tr>
    <th>名稱</th>
    <!-- <th>封面圖像網址</th> -->
    <!-- <th>網上閱讀網址</th>     -->
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.name %></td>
    <td><%= link_to I18n.t('home.link.rate_this'), new_comic_rating_path(comic) %></td>
    <td><%= link_to I18n.t('home.link.read_online'), comic.online_reading_website_url %></td>
  </tr>
<% end %>
</table>

app/views/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |

<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), comics_path %>
</div>

app/views/comics/index.html.erb
<h1><%= I18n.t('comics.list.title') %></h1>

<div id="help-links" class="suggest-comics">
  <%= suggest_comics_link %>
</div>

<table>
  <tr>
    <th>名稱</th>
    <th>作者</th>
    <!-- <th>封面圖像網址</th> -->
    <!-- <th>網上閱讀網址</th>     -->
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.name %></td>
    <td><%= comic.author %></td>
    <td><%= link_to I18n.t('home.link.rate_this'), new_comic_rating_path(comic) %></td>
    <td><%= link_to I18n.t('home.link.read_online'), "http://dm.99770.com" %></td>    
  </tr>
<% end %>
</table>

app/views/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), comics_path %>
</div>

app/views/comics/show.html.erb
<p>
  <b>Name:</b>
  <%= @comic.name %>
</p>

<p>
  <b>Author:</b>
  <%= @comic.author %>
</p>

<p>
  <b>Book cover image url:</b>
  <%= @comic.book_cover_image_url %>
</p>


<%= link_to I18n.t('link.edit'), edit_comic_path(@comic) %> |
<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), comics_path %>
</div>