config/routes.rb
BestComics::Application.routes.draw do
  resources :comic_requests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :comics do
    resources :ratings, :controller => "comic_ratings"
  end
  
  resources :users do
    resources :ratings
  end
  
  match 'user_comic_list/:user_name' => 'ratings#user_comic_list', :as => "user_comic_list"
  match 'comics/author/:author_name' => 'comics#author_search'
  
  root :to => "home#index"

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :comic
  
  validates_inclusion_of :rating, :in => 1..10
  
  after_save :update_comic_statistics
  
  private
  
  def update_comic_statistics
    self.comic.update_statistics!
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = current_user.ratings.order("rating DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = current_user.ratings.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = current_user.ratings.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = current_user.ratings.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    @rating = current_user.ratings.build(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(user_ratings_path(current_user), :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = current_user.ratings.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to(user_ratings_path(current_user), :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = current_user.ratings.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(user_ratings_path(current_user)) }
      format.xml  { head :ok }
    end
  end
  
  def user_comic_list
    users = User.where(:username => params[:user_name])
    @user = users.first if users.any?
    @ratings = @user.ratings.order("rating DESC") if @user
    @meta_title = I18n.t("layout.user_meta.title", :user_name => @user.username) if @user
    @meta_description = I18n.t("layout.user_meta.description", :user_name => @user.username) if @user
  end  
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def comics_option_for_select(selected)
    options_from_collection_for_select(Comic.all, "id", "name", selected)
  end
  
  def ratings_option_for_select(selected)
    options_for_select((1..10).map{|num| [num, num]}, selected)
  end
end

app/views/ratings/_form.html.erb
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comic_id, I18n.t('comics.comic_name') %><br />
    <%= f.select :comic_id, comics_option_for_select(@rating.comic_id) %>
    <%= suggest_comics_link %>
  </div>
  <div class="field">
    <%= f.label :rating, I18n.t('comics.rating') %><br />
    <%= f.select :rating, ratings_option_for_select(@rating.rating) %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('link.save') %>
  </div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= form_for(@rating, :url => user_rating_path(current_user)) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), user_ratings_path(current_user) %>
</div>

app/views/ratings/index.html.erb
<h1><%= I18n.t("user_ratings.title") %></h1>
<h3 id="share-this"><%= I18n.t("user_ratings.share_this") %> <%= link_to user_comic_list_url(:user_name => current_user.username), user_comic_list_url(:user_name => current_user.username) %></h3>

<div id="your-comic-list">
<table>
  <tr>
    <th><%= I18n.t("user_ratings.comic_name") %></th>
    <th><%= I18n.t("user_ratings.author_name") %></th>    
    <th><%= I18n.t("user_ratings.rating") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.comic.name %></td>
    <td><%= link_to rating.comic.author, "/comics/author/#{rating.comic.author}" %></td>
    <td><%= rating.rating %></td>
    <td><%= link_to I18n.t('link.edit'), edit_user_rating_path(current_user, rating) %></td>
    <td><%= link_to I18n.t('link.destroy'), user_rating_path(current_user, rating), :confirm => I18n.t('link.confirm'), :method => :delete %></td>
  </tr>
<% end %>
</table>

</div>

<%= link_to I18n.t("user_ratings.link.new_rating"), new_user_rating_path(current_user) %>

app/views/ratings/new.html.erb
<h1><%= I18n.t('user_ratings.new_rating_title') %></h1>

<%= form_for([current_user, @rating]) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), user_ratings_path(current_user) %>
</div>

app/views/ratings/show.html.erb
<p>
  <b>User:</b>
  <%= @rating.user.email %>
</p>

<p>
  <b>Comic:</b>
  <%= @rating.comic.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @rating.rating %>
</p>


<%= link_to I18n.t('link.edit'), edit_rating_path(@rating) %> |
<div class="back-link link-to-actions">
<%= link_to I18n.t('link.back'), ratings_path %>
</div>

app/views/ratings/user_comic_list.html.erb
<h1>
  <%= "#{@user.username} #{I18n.t('user_ratings.comic_list_title')}" %>
  <span id="share-button">
    <a id="facebook-share-button" href="http://www.facebook.com/sharer.php?u=<%= request.url %>&t=See which comics are recommended by the crowd"><img src="/images/fb_share_button.png" /></a>          
  </span>
</h1>

<table>
  <tr>
    <th><%= I18n.t("user_ratings.comic_name") %></th>
    <th><%= I18n.t("user_ratings.rating") %></th>
    <th></th>
    <th></th>    
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.comic.name %></td>
    <td><%= rating.rating %></td>
    <td><%= link_to I18n.t('home.link.rate_this'), new_comic_rating_path(rating.comic) %></td>
    <td><%= link_to I18n.t('home.link.read_online'), "http://dm.99770.com" %></td>    
  </tr>
<% end %>
</table>