config/routes.rb
BestComics::Application.routes.draw do
  resources :comic_requests

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :comics do
    resources :ratings, :controller => "comic_ratings"
  end
  
  resources :users do
    resources :ratings
  end
  
  match 'user_comic_list/:user_name' => 'ratings#user_comic_list', :as => "user_comic_list"
  match 'comics/author/:author_name' => 'comics#author_search'
  
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= meta_title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <meta content="<%= meta_description %>" name='description'/> 
  <meta content='ruby,rails,scala,hong kong,developer,3dd13,comics' name='keywords'/> 
  <meta content='RU05,3dd13,Benny Ng,Steven Wong' name='author'/> 
  <meta content='index,follow' name='robots'/>
  <meta property="fb:admins" content="667250212" />
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-22967267-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
  <div id="container">
  <header>
    <div id="header">
      <div id="header-logo">
        <h3>
          <%= link_to I18n.t('home.title'),  "/" %>
        </h3>
        <h4 id="header-tagline">
          <%= I18n.t('home.tagline') %>
        </h4>
      </div>
      <div id="header-menu">       
        <nav id="navigation-menu">
          <ul>
            <li><%= link_to I18n.t('layout.menu.search_comics'), comics_path %></li>            
           <% if current_user %>
             <li><%= link_to I18n.t('layout.menu.your_best_comics'), user_ratings_path(current_user) %></li>
             <li><%= link_to I18n.t('layout.menu.logout'), destroy_user_session_path %></li>
           <% else %>
             <li><%= link_to I18n.t('layout.menu.signup'), new_registration_path("user") %></li>
             <li><%= link_to I18n.t('layout.menu.login'), new_session_path("user") %></li>
           <% end %>
          </ul>
        </nav>
        <div id="facebook-like-buttons">
          <div id="like-button">
          <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fcomics-crowd.heroku.com&amp;send=false&amp;layout=standard&amp;width=300&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowTransparency="true"></iframe>
          </div>
        </div>
      </div>
    </div>
  </header>
  
  <div id="content">
    <div id="flash-notices">
    <% ([:error, :notice] & flash.keys).each do |key| %>      
    <%= content_tag :p, flash[key], :class => "flash_display flash_#{key.to_s.underscore}" %> 
    <% end %>
    </div>
    <%= yield %>
  </div>

  <footer>
    <div id="footer">
      <div id="footer-menu">
        <ul>
          <li><a href="https://github.com/3dd13/comics-crowd/issues">Feedbacks</a> | </li>                    
          <li>Powered by: </li>
          <li><a href="http://ru05team.blogspot.com">Ru05</a> @ </li>          
          <li><a href="https://github.com/3dd13/comics-crowd">3dd13</a></li>
        </ul>
      </div>
    </div>
  </footer>
  
  </div>  
</body>
</html>